### ISSUE TITLE
Having error_speech_timeout - true on Android 9+ using the example code.

### ISSUE THREAD

**Issue by carloselborges** [csdcorp/speech_to_text#143]
I'm always getting the **error_speech_timeout** using the example code.
(I did a screen before the sample just to choose between libraries tests).

Steps to reproduce:
- Run the app sample code.
- Click on `Initialize`.
- Click on `start`.
- It always show the **error_speech_timeout - true** on **Error Status**.

This happened on the current versions:

- **Pub.dev install tab version**
```
dependencies:
  speech_to_text: ^2.7.0
```

- **Git main branch (59932ef)**
```
dependencies:
  speech_to_text:
    git:
      url: https://github.com/csdcorp/speech_to_text.git
      ref: main
```

Print screen below.
I found some others issues with the same message, but no resolution (or missed by mistake).
Thanks in advance for your attention.

![flutter_01](https://user-images.githubusercontent.com/8053395/95245354-65b3f900-07e9-11eb-828c-60f70153bf81.png)
